version: '3.7'

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: realize start --run --no-config
    ports:
      - 1323:1323
    environment:
      - PORT=1323
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - DB_DATABASE=echodb

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=echodb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
